version: 2

jobs:
  build:
    docker:
      - image: docker/compose:1.23.2
    steps:
      - checkout
      - run:
          name: install
          command: |
            cp docker-compose.local.yaml docker-compose.override.yaml
            docker-compose up -d
      - run:
          name: lint
          command: docker-compose exec api npm run lint
