version: 2

jobs:
  build:
    docker:
      - image: docker/compose:1.25.5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install
          command: |
            docker-compose -f docker-compose.yaml -f docker-compose.local.yaml -f docker-compose.local.ci.yaml up -d
      - run:
          name: lint
          command: |
            docker-compose exec api npm run lint
      - run:
          name: test
          command: |
            docker-compose exec -u root api mkdir -p data/audio
            docker-compose exec -u root api chown -R node:node data
            docker-compose exec api npm run test
