version: 2

jobs:
  build:
    docker:
      - image: docker/compose:1.23.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install
          command: |
            docker-compose -f docker-compose.yaml -f docker-compose.local.yaml -f docker-compose.ci.yaml up -d
      - run:
          name: lint
          command: |
            docker-compose exec api npm run lint
